//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5032_asg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toured
    {
        public int Passenger_Id { get; set; }
        public string Cruise_Id { get; set; }
        public string Tour_Id { get; set; }
        public string Date { get; set; }
        public int PassengerPassenger_Id { get; set; }
        public int CruiseCruise_Id { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Cruise Cruise { get; set; }
    }
}
