//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5032_asg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vist
    {
        public int Cruise_Id { get; set; }
        public string Port_Name { get; set; }
        public string Country { get; set; }
        public string Arrive_Date { get; set; }
        public string Departure_Date { get; set; }
        public int CruiseCruise_Id { get; set; }
    
        public virtual Cruise Cruise { get; set; }
    }
}
